CREATE TABLE SMS_USERS_GROUP1 (
	USER_ID 			VARCHAR2(20)	NOT NULL
  , PASSWORD			VARCHAR2(100)	NOT NULL
  , FIRST_NAME			VARCHAR2(50)	NOT NULL
  , LAST_NAME			VARCHAR2(50)	NOT NULL
  , MIDDLE_INITIAL		VARCHAR2(3)		NOT NULL
  , EMAIL				VARCHAR2(100)
  , ACTIVE_TAG			VARCHAR2(1)		NOT NULL
  , ACCESS_LEVEL		VARCHAR2(1)		NOT NULL
  , ENTRY_DATE			DATE			NOT NULL
  , LAST_LOGIN			DATE			NOT NULL
  , LAST_USER			VARCHAR2(20)	NOT NULL
  );
  ALTER TABLE SMS_USERS_GROUP1
  ADD CONSTRAINT USER_PK_GROUP1	PRIMARY KEY(USER_ID); 
  
CREATE TABLE SUPPLY_TYPES_GROUP1 (
	SUPPLY_TYPE_ID		NUMBER(15)		NOT NULL	/* GROUP1_SUPPLY_TYPE_SEQ */
  , TYPE_NAME			VARCHAR2(100)	NOT NULL
  , ENTRY_DATE			DATE			NOT NULL
  , LAST_USER			VARCHAR2(20)	NOT NULL
  , LAST_UPDATE			DATE			NOT NULL
);

	ALTER TABLE SUPPLY_TYPES_GROUP1
	ADD CONSTRAINT SUP_TYPE_PK_GROUP1	PRIMARY KEY(SUPPLY_TYPE_ID);
	
	
CREATE TABLE SUPPLIES_GROUP1(
	SUPPLY_ID			NUMBER(15)  	NOT NULL	/* GROUP1_SUPPLY_ID_SEQ */
  ,	SUPPLY_TYPE_ID		NUMBER(15)		NOT NULL
  , ITEM_NAME			VARCHAR2(100)	NOT NULL
  , ITEM_UNIT			VARCHAR2(10)	NOT NULL
  , OBSOLETE_TAG		VARCHAR2(1)	
  , LOCATION			VARCHAR2(100)	
  , REORDER_LEVEL		NUMBER(4)
  , ACTUAL_COUNT		NUMBER(4)		NOT NULL
  , REMARKS				VARCHAR2(1000)
  , DATE_ADDED			DATE			NOT NULL
  , LAST_USER			VARCHAR2(20)	NOT NULL
  , LAST_UPDATE			DATE			NOT NULL
);	

	ALTER TABLE SUPPLIES_GROUP1
	ADD CONSTRAINT 
		SUPPLY_ID_PK_GROUP1 PRIMARY KEY (SUPPLY_ID)	
    ADD CONSTRAINT SUPPLY_TYPE_ID_FK_GROUP1 FOREIGN KEY (SUPPLY_TYPE_ID) 
		REFERENCES	SUPPLY_TYPES_GROUP1 (SUPPLY_TYPE_ID);
	
CREATE TABLE ISSUED_SUPPLIES_GROUP1(
	ISSUE_ID			NUMBER(15) 		NOT NULL 	/* GROUP1_ISSUED_ID_SEQ */
  , SUPPLY_ID			NUMBER(15)		NOT NULL
  , ISSUE_DATE			DATE			NOT NULL
  , REQUESTOR			VARCHAR2(100)	NOT NULL
  , QUANTITY			NUMBER(4)		NOT NULL
  , DEPT_ID				VARCHAR2(3)		NOT NULL
  , LAST_USER			VARCHAR2(20)	NOT NULL
  , LAST_UPDATE			DATE			NOT NULL
);

	ALTER TABLE ISSUED_SUPPLIES_GROUP1
	ADD CONSTRAINT ISSUE_ID_PK_GROUP1	PRIMARY KEY (ISSUE_ID)
	ADD CONSTRAINT SUPPLY_ID_FK_GROUP1	FOREIGN KEY (SUPPLY_ID)
		REFERENCES	SUPPLIES_GROUP1(SUPPLY_ID);
		
CREATE TABLE SUPPLIES_STOCKS_GROUP1(
	STOCK_ID			NUMBER(15) 		NOT NULL 	/* GROUP1_STOCK_ID_SEQ */
  , SUPPLY_ID			NUMBER(15)		NOT NULL
  , DATE_ADDED			DATE			NOT NULL
  , PURCHASE_DATE		VARCHAR2(100)	
  , REFERENCE_NO		NUMBER(4)		
  , QUANTITY			VARCHAR2(3)		NOT NULL
  , LAST_USER			VARCHAR2(20)	NOT NULL
  , LAST_UPDATE			DATE			NOT NULL
);

	ALTER TABLE ISSUED_SUPPLIES_GROUP1
	ADD CONSTRAINT STOCK_ID_PK_GROUP1	PRIMARY KEY (STOCK_ID)
	ADD CONSTRAINT SUPPLY_STOCK_FK_GROUP1	FOREIGN KEY (SUPPLY_ID)
		REFERENCES	SUPPLIES_GROUP1(SUPPLY_ID);		
	
	
DROP  TABLE SMS_USERS_GROUP1;	
DROP  TABLE SUPPLY_TYPES_GROUP1;
DROP  TABLE SUPPLIES_GROUP1;	
DROP  TABLE ISSUED_SUPPLIES_GROUP1;		
DROP  TABLE SUPPLIES_STOCKS_GROUP1;    




--DROP SEQUENCE GROUP1_SUPPLY_TYPE_SEQ;

CREATE SEQUENCE GROUP1_SUPPLY_TYPE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  select GROUP1_SUPPLY_TYPE_SEQ.nextval from dual;
  
CREATE SEQUENCE GROUP1_SUPPLY_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  select GROUP1_SUPPLY_ID_SEQ.nextval from dual;
  
CREATE SEQUENCE GROUP1_ISSUED_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  select GROUP1_ISSUED_ID_SEQ.nextval from dual;  
  

CREATE SEQUENCE GROUP1_STOCK_ID_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  select GROUP1_STOCK_ID_SEQ.nextval from dual;    
  




INSERT
INTO    SMS_USERS_GROUP1
       (user_id
      , password
      , first_name
      , last_name
      , middle_initial
      , email
      , active_tag
      , access_level
      , entry_date
      , last_login
      , last_user)
VALUES ('admin'
      , 'admin'
      , 'admin'
      , 'admin'
      , 'A'
      , 'admin@admin.com'
      , 'Y'
      , 'A'
      , SYSDATE
      , SYSDATE
      , 'admin');
      
   
   select * from SMS_USERS_GROUP1;
   
